// src/components/AppSelectItem.vue
<template>
  <SelectItem class="app-select-item" :value="itemValue" :disabled="disabled">
    <SelectItemText><slot /></SelectItemText>
    <SelectItemIndicator class="app-select-item-indicator"><CheckIcon :size="14" /></SelectItemIndicator>
  </SelectItem>
</template>

<script>
import { SelectItem, SelectItemIndicator, SelectItemText } from "reka-ui";
import { Check as CheckIcon } from "@lucide/vue";
import { EMPTY_SELECT_VALUE } from "./appSelectEmptyValue.js";

export default {
  components: { SelectItem, SelectItemIndicator, SelectItemText, CheckIcon },
  props: {
    value: { type: [String, Number], required: true },
    disabled: { type: Boolean, default: false }
  },
  computed: {
    itemValue() {
      return String(this.value) === "" ? EMPTY_SELECT_VALUE : String(this.value);
    }
  }
};
</script>

// web/components/ui/AppSelectItem.jsx
"use client";

import { Select } from "radix-ui";
import { Check } from "lucide-react";
import { EMPTY_SELECT_VALUE } from "../../lib/selectEmptyValue";

export default function AppSelectItem({ value, disabled = false, children }) {
  const itemValue = String(value) === "" ? EMPTY_SELECT_VALUE : String(value);
  return (
    <Select.Item className="app-select-item" value={itemValue} disabled={disabled}>
      <Select.ItemText>{children}</Select.ItemText>
      <Select.ItemIndicator className="app-select-item-indicator">
        <Check size={14} />
      </Select.ItemIndicator>
    </Select.Item>
  );
}
