// src/components/Modal.vue
<template>
  <DialogRoot :open="modelValue" @update:open="$emit('update:modelValue', $event)">
    <DialogPortal>
      <DialogOverlay class="modal-shell" />
      <DialogContent class="modal-card" :class="cardClass">
        <div class="dialog-head">
          <DialogTitle as-child><h2><slot name="title" /></h2></DialogTitle>
          <DialogClose as-child>
            <button class="icon-button" type="button" :aria-label="closeLabel"><XIcon :size="20" /></button>
          </DialogClose>
        </div>
        <slot />
      </DialogContent>
    </DialogPortal>
  </DialogRoot>
</template>

<script>
import { DialogClose, DialogContent, DialogOverlay, DialogPortal, DialogRoot, DialogTitle } from "reka-ui";
import { X as XIcon } from "@lucide/vue";

export default {
  components: { DialogClose, DialogContent, DialogOverlay, DialogPortal, DialogRoot, DialogTitle, XIcon },
  props: {
    modelValue: { type: Boolean, default: false },
    cardClass: { type: String, default: "" },
    closeLabel: { type: String, default: "Close" }
  },
  emits: ["update:modelValue"]
};
</script>

// web/components/ui/Modal.jsx
"use client";

import { Dialog } from "radix-ui";
import { X } from "lucide-react";
import { motion } from "framer-motion";

export default function Modal({ open, onOpenChange, cardClass = "", closeLabel = "Close", title, children }) {
  return (
    <Dialog.Root open={open} onOpenChange={onOpenChange}>
      <Dialog.Portal>
        <Dialog.Overlay asChild>
          <motion.div className="modal-shell" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} transition={{ duration: 0.15 }} />
        </Dialog.Overlay>
        <Dialog.Content asChild>
          <motion.div
            className={`modal-card${cardClass ? ` ${cardClass}` : ""}`}
            initial={{ opacity: 0, scale: 0.97, y: 8 }}
            animate={{ opacity: 1, scale: 1, y: 0 }}
            exit={{ opacity: 0, scale: 0.97, y: 8 }}
            transition={{ duration: 0.16 }}
          >
            <div className="dialog-head">
              <Dialog.Title asChild>
                <h2>{title}</h2>
              </Dialog.Title>
              <Dialog.Close asChild>
                <button className="icon-button" type="button" aria-label={closeLabel}>
                  <X size={20} />
                </button>
              </Dialog.Close>
            </div>
            {children}
          </motion.div>
        </Dialog.Content>
      </Dialog.Portal>
    </Dialog.Root>
  );
}
