// web/components/ui/AppSelect.jsx
"use client";

import { Select } from "radix-ui";
import { ChevronDown, ChevronUp } from "lucide-react";
import { EMPTY_SELECT_VALUE } from "../../lib/selectEmptyValue";

// React port of src/components/AppSelect.vue — same prop shape (value/onChange
// instead of v-model) and same empty-string sentinel handling.
export default function AppSelect({ value, onChange, placeholder = "", number = false, className, children, ...triggerProps }) {
  const stringValue = value === null || value === undefined || value === "" ? EMPTY_SELECT_VALUE : String(value);

  function handleChange(next) {
    const raw = next === EMPTY_SELECT_VALUE ? "" : next;
    onChange?.(number ? Number(raw) : raw);
  }

  return (
    <Select.Root value={stringValue} onValueChange={handleChange}>
      <Select.Trigger className={`app-select-trigger${className ? ` ${className}` : ""}`} {...triggerProps}>
        <Select.Value placeholder={placeholder} />
        <Select.Icon className="app-select-icon">
          <ChevronDown size={16} />
        </Select.Icon>
      </Select.Trigger>
      <Select.Portal>
        <Select.Content className="app-select-content" position="popper" sideOffset={6} align="start">
          <Select.ScrollUpButton className="app-select-scroll">
            <ChevronUp size={14} />
          </Select.ScrollUpButton>
          <Select.Viewport className="app-select-viewport">{children}</Select.Viewport>
          <Select.ScrollDownButton className="app-select-scroll">
            <ChevronDown size={14} />
          </Select.ScrollDownButton>
        </Select.Content>
      </Select.Portal>
    </Select.Root>
  );
}

// src/components/AppSelect.vue
<template>
  <SelectRoot :model-value="stringValue" @update:model-value="handleUpdate">
    <SelectTrigger class="app-select-trigger" v-bind="$attrs">
      <SelectValue :placeholder="placeholder" />
      <SelectIcon class="app-select-icon"><ChevronDownIcon :size="16" /></SelectIcon>
    </SelectTrigger>
    <SelectPortal>
      <SelectContent class="app-select-content" position="popper" :side-offset="6" align="start">
        <SelectScrollUpButton class="app-select-scroll"><ChevronUpIcon :size="14" /></SelectScrollUpButton>
        <SelectViewport class="app-select-viewport">
          <slot />
        </SelectViewport>
        <SelectScrollDownButton class="app-select-scroll"><ChevronDownIcon :size="14" /></SelectScrollDownButton>
      </SelectContent>
    </SelectPortal>
  </SelectRoot>
</template>

<script>
import { SelectContent, SelectIcon, SelectPortal, SelectRoot, SelectScrollDownButton, SelectScrollUpButton, SelectTrigger, SelectValue, SelectViewport } from "reka-ui";
import { ChevronDown as ChevronDownIcon, ChevronUp as ChevronUpIcon } from "@lucide/vue";
import { EMPTY_SELECT_VALUE } from "./appSelectEmptyValue.js";

export default {
  inheritAttrs: false,
  components: { SelectContent, SelectIcon, SelectPortal, SelectRoot, SelectScrollDownButton, SelectScrollUpButton, SelectTrigger, SelectValue, SelectViewport, ChevronDownIcon, ChevronUpIcon },
  props: {
    modelValue: { type: [String, Number], default: "" },
    modelModifiers: { default: () => ({}) },
    placeholder: { type: String, default: "" }
  },
  emits: ["update:modelValue"],
  computed: {
    stringValue() {
      const value = this.modelValue === null || this.modelValue === undefined ? "" : String(this.modelValue);
      return value === "" ? EMPTY_SELECT_VALUE : value;
    }
  },
  methods: {
    handleUpdate(value) {
      const raw = value === EMPTY_SELECT_VALUE ? "" : value;
      this.$emit("update:modelValue", this.modelModifiers.number ? Number(raw) : raw);
    }
  }
};
</script>
